### ISSUE TITLE
`info` div isn't always displayed next to the selected item

### ISSUE THREAD

**Issue by erictapen** [uclab-potsdam/wimmelvis#16]
On chromium (and I think Mariana and I also saw it on Safari) I'm seeing this behaviour where the view in the svg always moves into the upper left corner after clicking an item.

Desired behaviour would be, that the infobox opens roughly next to the item and the svg view doesn't pan.

https://user-images.githubusercontent.com/11532355/179508950-aee2823a-4ae5-4fe4-bd7b-e40580cbbb13.mp4

**Comment by more-ginger** [comment]
It seems to be solved for me, at least on Safari.
