### ISSUE TITLE
Missing icons and assets

### ISSUE THREAD

**Issue by more-ginger** [uclab-potsdam/wimmelvis#21]

**Comment by erictapen** [comment]
To me it looks like there are only the icons for old clothing missing:

- [ ] `old-clothing_w_symbol.png` and `old-clothing-BN.png`

**Comment by more-ginger** [comment]
Yes, true! I am also using a different icon for `chain-of-lights-BN.png` because of legibility when the icon is too small. You can find the file in common > assets > items
